"""add_expires_at_to_booking

Revision ID: 632eb1968e23
Revises: a8a26fef844c
Create Date: 2025-07-09 16:26:41.789156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '632eb1968e23'
down_revision: Union[str, Sequence[str], None] = 'a8a26fef844c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('expires_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'expires_at')
    # ### end Alembic commands ###
