"""add_expires_at_to_booking

Revision ID: b1b2c3d4e5f6
Revises: a8a26fef844c
Create Date: 2025-01-09 00:00:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b1b2c3d4e5f6"
down_revision = "a8a26fef844c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bookings", sa.Column("expires_at", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bookings", "expires_at")
    # ### end Alembic commands ###
